name: afrikalyrics_mobile
description: A new Flutter project.
publish_to: 'none'
version: 2.0.5+10
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  dio: ^4.0.0 # regressed
  dio_http_cache: ^0.3.0
  get_it: ^7.6.7
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  youtube_player_flutter: ^9.0.0 
  line_icons: ^2.0.3
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  json_pretty: ^1.0.4
  flutter_html: ^3.0.0-beta.2 #^2.2.1
  # flutter_audio_query:
  #   git:
  #     url: https://github.com/Gnac05/gnac_flutter_audio_query.git
  #     ref: development
  #assets_audio_player: ^2.0.13+1 lukhof
  assets_audio_player: ^3.1.1
  #just_audio: ^0.6.5
  firebase_core: ^2.26.0
  google_sign_in: ^6.2.1
  firebase_messaging: ^14.7.18
  firebase_analytics: ^10.8.8
  firebase_crashlytics: ^3.4.17
  flutter_local_notifications: ^17.0.0
  image_downloader: ^0.31.0
  debounce_throttle: ^2.0.0
  marquee_widget: ^1.2.0
  in_app_purchase: ^0.4.0 # regressed
  slugify: ^2.0.0
  share_plus: ^2.0.0 # regressed
  flutter_lrc:
    git: 
      url: https://github.com/loicgeek/flutter_lrc.git 
  
  #for favorite and maching lyric
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # For OS-specific directory paths
  path_provider: ^2.0.0 # regressed
  file_picker: ^3.0.0 # regressed
  permission_handler: ^11.3.0
  flutter_ringtone_player: ^3.0.0 # regressed
  get_storage: ^2.1.1
  url_launcher: ^6.2.5
  google_fonts: ^4.0.4 #^2.0.0 #regressed
  package_info_plus: ^1.0.0 # regressed
  move_to_background: ^1.0.2
  on_audio_query: ^2.9.0
  google_mobile_ads: ^2.4.0
  # flutter_layout_grid: ^2.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0 # regressed
  hive_generator: ^1.0.1 # regressed
  build_runner: ^2.0.0 # regressed
  flutter_splash_screen: ^3.0.0
  # flutter_native_splash: ^2.3.13

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-circle.jpg"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
